
% use Huffman code to get RUNLENGTH | SIZE 
% valuelist: a cell containing the distinct SIZE (for DC) or RUNLENGTH|SIZE (for AC) values
% huffmancode: a cell containing the Huffman Code table generated by the buildHuffmanTable() function
function codeword = getValueByCode(huffmancode, huffmancodelist, valuelist)
	codeword='';
	for i=1:length(huffmancodelist)
		if strcmp(huffmancode, huffmancodelist{i})
            codeword = valuelist{i};
		end
	end
end
